[package]
name = "dnd_dice"
version = "0.1.0"
authors = ["Robert Setter <r.setter@comcast.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input-stream = "0.4.0"
rand = "0.8.3"
